-- SHOW DATABASES;
-- DROP DATABASE puppydb;
CREATE DATABASE puppydb DEFAULT CHARACTER SET UTF8MB4;
USE puppydb;

-- 건강, 간식 제외 테이블
CREATE TABLE conditionTBL (
	regdate DATE PRIMARY KEY,
	emotion VARCHAR(30)	COMMENT '기분상태',
	walk VARCHAR(30) 	COMMENT '산책유무',
	bath VARCHAR(30)	COMMENT '목욕유무',
	feed VARCHAR(30)	COMMENT '사료급여'
) DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE healthTBL (
	regdate DATE NOT NULL,
	health VARCHAR(30)
) DEFAULT CHARACTER SET UTF8MB4;

CREATE TABLE treatsTBL (
	regdate DATE NOT NULL,
	treats VARCHAR(30)
) DEFAULT CHARACTER SET UTF8MB4;
